import { StyleSheet } from 'react-native';
import { colors, layout } from './theme';

export const portfolioStyles = StyleSheet.create({
  content: { padding: layout.screenPadding, paddingBottom: 42 },
  header: { marginBottom: 18 },
  eyebrow: { color: colors.brand, fontSize: 12, fontWeight: '800', letterSpacing: 1.4 },
  title: { color: colors.text, fontSize: 34, fontWeight: '800', letterSpacing: -0.8, marginTop: 5 },
  subtitle: { color: colors.textMuted, fontSize: 14, lineHeight: 20, marginTop: 7 },
  summary: { backgroundColor: colors.brandDark, borderColor: '#4C3B79', borderWidth: 1, borderRadius: layout.cardRadius, padding: 18 },
  summaryLabel: { color: colors.brandSoft, fontSize: 11, fontWeight: '800', letterSpacing: 1.1 },
  summaryValue: { color: colors.text, fontSize: 32, fontWeight: '800', letterSpacing: -0.8, marginTop: 5 },
  summaryGain: { color: '#62D9A5', fontSize: 14, fontWeight: '800', marginTop: 5 },
  summaryLoss: { color: '#FB7185', fontSize: 14, fontWeight: '800', marginTop: 5 },
  sectionTitle: { color: colors.textMuted, fontSize: 11, fontWeight: '800', letterSpacing: 1.1, marginTop: 25, marginBottom: 10 },
  form: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: layout.cardRadius, padding: 16 },
  inputRow: { flexDirection: 'row', gap: 10, marginBottom: 10 },
  inputWrap: { flex: 1 },
  inputLabel: { color: colors.textMuted, fontSize: 10, fontWeight: '800', letterSpacing: 0.7, marginBottom: 6 },
  input: { color: colors.text, backgroundColor: colors.surfacePressed, borderColor: colors.border, borderWidth: 1, borderRadius: 12, paddingHorizontal: 12, paddingVertical: 11, fontSize: 14 },
  addButton: { backgroundColor: colors.brand, borderRadius: 13, alignItems: 'center', paddingVertical: 14, marginTop: 3 },
  addButtonText: { color: colors.textOnBrand, fontSize: 14, fontWeight: '800' },
  helper: { color: colors.textSubtle, fontSize: 11, lineHeight: 16, marginTop: 10 },
  holding: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 16, padding: 15, marginBottom: 10 },
  holdingTop: { flexDirection: 'row', justifyContent: 'space-between' },
  symbol: { color: colors.text, fontSize: 18, fontWeight: '800' },
  shares: { color: colors.textMuted, fontSize: 12, marginTop: 3 },
  holdingValue: { color: colors.text, fontSize: 16, fontWeight: '800', textAlign: 'right' },
  price: { color: colors.textMuted, fontSize: 12, marginTop: 3, textAlign: 'right' },
  gain: { color: '#62D9A5', fontSize: 12, fontWeight: '800', marginTop: 11 },
  loss: { color: '#FB7185', fontSize: 12, fontWeight: '800', marginTop: 11 },
  holdingFooter: { flexDirection: 'row', justifyContent: 'space-between', alignItems: 'center' },
  remove: { color: '#FDA4AF', fontSize: 12, fontWeight: '700', marginTop: 11 },
  refreshButton: { backgroundColor: colors.surfacePressed, borderColor: colors.border, borderWidth: 1, borderRadius: 13, alignItems: 'center', paddingVertical: 14, marginBottom: 10 },
  refreshText: { color: colors.brandSoft, fontSize: 14, fontWeight: '800' },
  empty: { color: colors.textMuted, textAlign: 'center', lineHeight: 20, paddingVertical: 28 },
  disclaimer: { color: colors.textSubtle, fontSize: 11, lineHeight: 16, textAlign: 'center', marginTop: 14 },
});
