import { StyleSheet } from 'react-native';
import { colors, layout } from './theme';

export const scannerStyles = StyleSheet.create({
  content: { padding: layout.screenPadding, paddingBottom: 42 },
  header: { marginBottom: 20 },
  eyebrow: { color: colors.brand, fontSize: 12, fontWeight: '800', letterSpacing: 1.4 },
  title: { color: colors.text, fontSize: 34, fontWeight: '800', letterSpacing: -0.8, marginTop: 5 },
  subtitle: { color: colors.textMuted, fontSize: 14, lineHeight: 20, marginTop: 7 },
  filterCard: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: layout.cardRadius, padding: 18 },
  filterLabel: { color: colors.textSecondary, fontSize: 12, fontWeight: '800', letterSpacing: 0.8, marginBottom: 9 },
  filterGroup: { marginBottom: 18 },
  chipRow: { flexDirection: 'row', flexWrap: 'wrap', gap: 8 },
  chip: { backgroundColor: colors.surfacePressed, borderColor: colors.border, borderWidth: 1, borderRadius: 99, paddingHorizontal: 13, paddingVertical: 8 },
  chipActive: { backgroundColor: colors.brand, borderColor: colors.brand },
  chipText: { color: colors.textSecondary, fontSize: 13, fontWeight: '700' },
  chipTextActive: { color: colors.textOnBrand },
  scanButton: { backgroundColor: colors.brand, borderRadius: layout.buttonRadius, paddingVertical: 16, alignItems: 'center' },
  scanButtonDisabled: { opacity: 0.65 },
  scanButtonText: { color: colors.textOnBrand, fontSize: 15, fontWeight: '800' },
  resultsHeader: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between', marginTop: 26, marginBottom: 10 },
  resultsTitle: { color: colors.textMuted, fontSize: 12, fontWeight: '800', letterSpacing: 1.2 },
  sourceBadge: { backgroundColor: colors.brandDark, borderRadius: 99, paddingHorizontal: 10, paddingVertical: 6 },
  sourceText: { color: colors.brandSoft, fontSize: 11, fontWeight: '800' },
  resultCard: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: 16, padding: 15, marginBottom: 10 },
  resultTop: { flexDirection: 'row', alignItems: 'center', justifyContent: 'space-between' },
  symbol: { color: colors.text, fontSize: 18, fontWeight: '800' },
  category: { color: colors.textMuted, fontSize: 12, marginTop: 3 },
  price: { color: colors.text, fontSize: 16, fontWeight: '700', textAlign: 'right' },
  gain: { color: '#62D9A5', fontSize: 13, fontWeight: '800', marginTop: 3, textAlign: 'right' },
  loss: { color: '#FB7185', fontSize: 13, fontWeight: '800', marginTop: 3, textAlign: 'right' },
  volume: { color: colors.textMuted, fontSize: 12, marginTop: 11 },
  empty: { color: colors.textMuted, textAlign: 'center', lineHeight: 20, paddingVertical: 28 },
  error: { color: '#FDA4AF', fontSize: 13, lineHeight: 19, marginTop: 12 },
  disclaimer: { color: colors.textSubtle, fontSize: 11, lineHeight: 16, textAlign: 'center', marginTop: 14 },
});
