import { StyleSheet } from 'react-native';
import { colors, layout } from './theme';

export const settingsStyles = StyleSheet.create({
  content: { padding: layout.screenPadding, paddingBottom: 42 },
  header: { marginBottom: 20 },
  eyebrow: { color: colors.brand, fontSize: 12, fontWeight: '800', letterSpacing: 1.4 },
  title: { color: colors.text, fontSize: 32, fontWeight: '800', letterSpacing: -0.8, marginTop: 5 },
  subtitle: { color: colors.textMuted, fontSize: 14, lineHeight: 20, marginTop: 7 },
  soundCard: { backgroundColor: colors.surface, borderColor: colors.border, borderWidth: 1, borderRadius: layout.cardRadius, overflow: 'hidden' },
  soundRow: { flexDirection: 'row', alignItems: 'center', paddingHorizontal: 16, paddingVertical: 17 },
  soundRowActive: { backgroundColor: colors.brandDark },
  soundDivider: { borderTopColor: colors.border, borderTopWidth: 1 },
  soundIcon: { width: 38, height: 38, borderRadius: 19, backgroundColor: colors.surfacePressed, alignItems: 'center', justifyContent: 'center', marginRight: 13 },
  soundIconText: { color: colors.brandSoft, fontSize: 20, fontWeight: '800' },
  optionText: { flex: 1 },
  optionTitle: { color: colors.text, fontSize: 15, fontWeight: '800' },
  optionDescription: { color: colors.textMuted, fontSize: 12, marginTop: 4 },
  selectionBadge: { width: 28, height: 28, borderRadius: 14, backgroundColor: colors.surfacePressed, alignItems: 'center', justifyContent: 'center' },
  selectionBadgeActive: { backgroundColor: colors.brand },
  selectionText: { color: colors.textMuted, fontSize: 19, fontWeight: '700', marginTop: -2 },
  selectionTextActive: { color: colors.textOnBrand, fontSize: 15, marginTop: 0 },
  previewNote: { color: colors.textSubtle, fontSize: 11, lineHeight: 16, marginTop: 10, marginBottom: 26 },
  sectionLabel: { color: colors.textMuted, fontSize: 11, fontWeight: '800', letterSpacing: 1.1, marginBottom: 10 },
  testButton: { backgroundColor: colors.surfacePressed, borderColor: colors.border, borderWidth: 1, borderRadius: layout.buttonRadius, paddingVertical: 15, alignItems: 'center' },
  testButtonText: { color: colors.brandSoft, fontSize: 14, fontWeight: '800' },
  infoCard: { backgroundColor: colors.surfaceElevated, borderRadius: 16, padding: 15, marginTop: 16 },
  infoTitle: { color: colors.brandSoft, fontSize: 13, fontWeight: '800' },
  infoText: { color: colors.textSecondary, fontSize: 12, lineHeight: 18, marginTop: 5 },
});
